-- Criação das tabelas para o Agente de IA (AdvFlow)
-- 1. Tabela de Configurações do Sistema
-- Armazena as chaves de API e URLs de integração.
-- Por segurança, recomenda-se habilitar RLS (Row Level Security) futuramente.
create table public.configuracoes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    gemini_api_key text,
    evolution_api_url text,
    evolution_api_key text,
    evolution_instance text,
    webhook_secret text
);
-- Insere um registro inicial vazio para garantir que o sistema sempre tenha o que atualizar
insert into public.configuracoes (id)
values (1);
-- 2. Tabela de Histórico de Mensagens
-- Armazena o contexto da conversa para o Gemini manter a memória.
create table public.mensagens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    whatsapp_id text not null,
    role text not null,
    -- 'user' ou 'model'
    content text
);
-- Indice para buscar mensagens rapidamente pelo ID do WhatsApp
create index idx_mensagens_whatsapp_id on public.mensagens(whatsapp_id);
-- 3. Tabela de Leads
-- Armazena os leads capturados e seu status no funil.
create table public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    whatsapp_id text not null unique,
    status text default 'Em Aberto',
    -- 'Em Aberto', 'Briefing Concluído', 'Em Produção'
    nome_advogado text,
    nome_escritorio text,
    especialidades text,
    diferencial text,
    resumo_briefing text
);
-- Função para atualizar o timestamp 'updated_at' automaticamente
create or replace function public.handle_updated_at() returns trigger as $$ begin new.updated_at = now();
return new;
end;
$$ language plpgsql;
create trigger leads_updated_at before
update on public.leads for each row execute procedure public.handle_updated_at();